In [15]:
import numpy as np
from sklearn.linear_model import LinearRegression
from IPython import display


Linear Regression

Step 1: Loading Dataset

In [2]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3

Step 2: Analysing the data

In [8]:
X,y

(array([[1, 1],
        [1, 2],
        [2, 2],
        [2, 3]]),
 array([ 6,  8,  9, 11]))

Step 3: Model Fitting

In [3]:
reg = LinearRegression().fit(X, y)

Step 4: Validating the model

In [4]:
reg.score(X, y)

1.0

In [12]:
coef = reg.coef_
reg.coef_

array([1., 2.])

In [13]:
intercept = reg.intercept_
reg.intercept_

3.000000000000001

Step 5: Predicting using the model

In [6]:
reg.predict(np.array([[3, 5]]))

array([16.])

How does this work ? let look at a very high level calculation

16.0